# Generated by Django 4.1.2 on 2022-12-28 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_listing',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='active_listing',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
