# Generated by Django 4.1.2 on 2022-12-29 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_active_listing_price_active_listing_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_listing',
            name='is_exist',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_shop', to='shop.active_listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
