# Generated by Django 4.1.2 on 2022-12-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_comment_timestamp_post_timestamp_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_taked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='00:00', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
    ]
